apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uxvrht7cx-python
  janus-idp.io/tekton: uxvrht7cx-python
  backstage.io/kubernetes-id: uxvrht7cx-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uxvrht7cx-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
